"""Constants for Panasonic TaiSEIA local integration."""

from homeassistant.components.climate import HVACMode

DOMAIN = "panasonic_taiseia_local"
MANUFACTURER = "Panasonic"
DEFAULT_NAME = "Panasonic TaiSEIA Local"
DEFAULT_PORT = 57223
DEFAULT_UPDATE_INTERVAL = 30

# Config entry kinds
ENTRY_TYPE_HUB = "hub"
ENTRY_TYPE_DEVICE = "device"
CONF_ENTRY_TYPE = "entry_type"
CONF_HUB_ENTRY_ID = "hub_entry_id"
CONF_USERNAME = "username"
CONF_PASSWORD = "password"
CONF_CP_TOKEN = "cp_token"
CONF_REFRESH_TOKEN = "refresh_token"
# CZ-T006 modules choke when many LAN clients hit SetSaanet at once (HA boot /
# aligned coordinator ticks). Defaults; overridable via shared LAN settings.
DEFAULT_REQUEST_TIMEOUT = 12.0
DEFAULT_MAX_CONCURRENT = 2
DEFAULT_REQUEST_RETRIES = 3
DEFAULT_REQUEST_RETRY_DELAY = 0.6
# Back-compat aliases
REQUEST_TIMEOUT = DEFAULT_REQUEST_TIMEOUT
MAX_CONCURRENT_REQUESTS = DEFAULT_MAX_CONCURRENT
REQUEST_RETRIES = DEFAULT_REQUEST_RETRIES
REQUEST_RETRY_DELAY = DEFAULT_REQUEST_RETRY_DELAY

CONF_REQUEST_TIMEOUT = "request_timeout"
CONF_REQUEST_RETRIES = "request_retries"
CONF_REQUEST_RETRY_DELAY = "request_retry_delay"
CONF_MAX_CONCURRENT = "max_concurrent"

PLATFORMS = [
    "climate",
    "humidifier",
    "sensor",
    "binary_sensor",
    "switch",
    "select",
    "number",
    "button",
]

DATA_CLIENT = "client"
DATA_COORDINATOR = "coordinator"
DATA_PROFILE = "profile"
DATA_ENERGY = "energy"
DATA_HOUSE_ENERGY = "_house_energy_setup"

CONF_HOST = "host"
CONF_NAME = "name"
CONF_UPDATE_INTERVAL = "update_interval"
CONF_DEVICE_TYPE = "device_type"
CONF_INDOOR_MODEL = "indoor_model"
CONF_MODEL_TYPE = "model_type"

# Energy options (cycle/reset_* are shared domain-wide; others per entry)
CONF_ENERGY_ENABLED = "energy_enabled"
CONF_ENERGY_INCLUDE_HOUSE = "energy_include_house"
CONF_ENERGY_CYCLE = "energy_cycle"
CONF_ENERGY_CYCLE_DAYS = "energy_cycle_days"
CONF_ENERGY_RESET_DAY = "energy_reset_day"
CONF_ENERGY_RESET_WEEKDAY = "energy_reset_weekday"
CONF_ENERGY_RESET_PERIOD = "energy_reset_period"
CONF_ENERGY_RESET_TOTAL = "energy_reset_total"

# Cloud metadata cached on device entries (from EMS)
CONF_CLOUD_NICKNAME = "cloud_nickname"
CONF_CLOUD_MODEL = "cloud_model"
CONF_CLOUD_MODEL_ID = "cloud_model_id"
CONF_CLOUD_MODEL_TYPE = "cloud_model_type"
CONF_CLOUD_DEVICE_TYPE = "cloud_device_type"
CONF_CLOUD_GWID = "cloud_gwid"

ENERGY_CYCLE_MONTHLY = "monthly"
ENERGY_CYCLE_DAILY = "daily"
ENERGY_CYCLE_WEEKLY = "weekly"
ENERGY_CYCLE_YEARLY = "yearly"
ENERGY_CYCLE_DAYS = "days"
ENERGY_CYCLE_NONE = "none"

DEFAULT_ENERGY_CYCLE = ENERGY_CYCLE_MONTHLY
DEFAULT_ENERGY_CYCLE_DAYS = 30
DEFAULT_ENERGY_RESET_DAY = 1
DEFAULT_ENERGY_RESET_WEEKDAY = 0  # Monday

ENERGY_CYCLE_OPTIONS = {
    ENERGY_CYCLE_MONTHLY: "每月（可指定幾號歸零）",
    ENERGY_CYCLE_DAILY: "每日（當地 0:00）",
    ENERGY_CYCLE_WEEKLY: "每週（可指定星期幾）",
    ENERGY_CYCLE_YEARLY: "每年（1/1）",
    ENERGY_CYCLE_DAYS: "每 N 天（可指定天數）",
    ENERGY_CYCLE_NONE: "不自動歸零（僅手動）",
}

ENERGY_WEEKDAY_OPTIONS = {
    0: "星期一",
    1: "星期二",
    2: "星期三",
    3: "星期四",
    4: "星期五",
    5: "星期六",
    6: "星期日",
}

# TaiSEIA type IDs
TYPE_REGISTER = 0x00
TYPE_AC = 0x01
TYPE_REFRIGERATOR = 0x02
TYPE_DEHUMIDIFIER = 0x04

DEVICE_TYPE_NAMES = {
    TYPE_AC: "冷氣",
    TYPE_REFRIGERATOR: "冰箱",
    TYPE_DEHUMIDIFIER: "除濕機",
}

REG_REGISTER = 0x00
REG_TYPE_ID = 0x04
REG_MODEL = 0x06
REG_SERVICES = 0x07
REG_ALL_STATES = 0x08

# ---- Shared / AC services ----
SVC_POWER = 0x00
SVC_MODE = 0x01
SVC_FAN = 0x02
SVC_TEMP_SET = 0x03
SVC_TEMP_IN = 0x04
SVC_SLEEP = 0x05
SVC_NANOE = 0x08
SVC_TIMER_ON = 0x0B
SVC_TIMER_OFF = 0x0C
SVC_SWING = 0x0F
SVC_SWING_LR = 0x11
SVC_FILTER_NOTIFY = 0x12
SVC_MOLD = 0x17
SVC_SELF_CLEAN = 0x18
SVC_MOTION = 0x19
SVC_TURBO = 0x1A
SVC_ECONAVI = 0x1B
SVC_BUZZER = 0x1E
SVC_INDICATOR = 0x1F
SVC_TEMP_OUT = 0x21
SVC_OPERATING_POWER = 0x27
SVC_PM25 = 0x37
SVC_PM25_FLAG = 0x38

# Dehumidifier
SVC_DH_OFF_TIMER = 0x02
SVC_DH_HUMIDITY_SET = 0x04
SVC_DH_HUMIDITY_IN = 0x07
SVC_DH_FAN_DIR = 0x09
SVC_DH_TANK = 0x0A
SVC_DH_NANOE = 0x0D
SVC_DH_FAN = 0x0E
SVC_DH_BUZZER = 0x18
SVC_DH_PM25 = 0x53
SVC_DH_ON_TIMER = 0x55
SVC_DH_PM10 = 0x56

# Refrigerator
SVC_RF_FREEZER_SET = 0x00
SVC_RF_FRIDGE_SET = 0x01
SVC_RF_FREEZER_TEMP = 0x03
SVC_RF_FRIDGE_TEMP = 0x05
SVC_RF_ECO = 0x0C
SVC_RF_DEFROST = 0x50
SVC_RF_STOP_ICE = 0x52
SVC_RF_QUICK_ICE = 0x53
SVC_RF_RAPID_FREEZE = 0x56
SVC_RF_PARTIAL_SET = 0x57
SVC_RF_PARTIAL_TEMP = 0x58
SVC_RF_WINTER = 0x5A
SVC_RF_SHOPPING = 0x5B
SVC_RF_VACATION = 0x5C
SVC_RF_NANOE = 0x61

STATUS = {i: f"0x{i:02X}" for i in range(0x00, 0x70)}

CLIMATE_AVAILABLE_MODE = [
    {"key": HVACMode.OFF, "mappingCode": -1},
    {"key": HVACMode.COOL, "mappingCode": 0},
    {"key": HVACMode.DRY, "mappingCode": 1},
    {"key": HVACMode.FAN_ONLY, "mappingCode": 2},
    {"key": HVACMode.AUTO, "mappingCode": 3},
    {"key": HVACMode.HEAT, "mappingCode": 4},
]
CLIMATE_AVAILABLE_FAN_MODE = {
    0: "自動", 1: "20%", 2: "40%", 3: "60%", 4: "80%", 5: "100%",
}
CLIMATE_AVAILABLE_SWING_MODE = {
    0: "自動", 1: "0°", 2: "20°", 3: "45°", 4: "70°", 5: "90°",
}
CLIMATE_AVAILABLE_SWING_LR = {
    0: "自動", 1: "1", 2: "2", 3: "3", 4: "4", 5: "5", 6: "6", 7: "7",
}
CLIMATE_AVAILABLE_INDICATOR = {0: "亮", 1: "暗", 2: "ECO燈滅"}
CLIMATE_AVAILABLE_MOTION = {0: "關", 1: "對人", 2: "不對人", 3: "自動"}
CLIMATE_MINIMUM_TEMPERATURE = 16
CLIMATE_MAXIMUM_TEMPERATURE = 30
CLIMATE_TEMPERATURE_STEP = 1.0
CLIMATE_ON_TIMER_MIN = 0
CLIMATE_ON_TIMER_MAX = 1440
CLIMATE_OFF_TIMER_MIN = 0
CLIMATE_OFF_TIMER_MAX = 1440

DEHUMIDIFIER_MIN_HUMD = 40
DEHUMIDIFIER_MAX_HUMD = 70
DEHUMIDIFIER_AVAILABLE_HUMIDITY = {
    0: 40, 1: 45, 2: 50, 3: 55, 4: 60, 5: 65, 6: 70,
}
DEHUMIDIFIER_AVAILABLE_MODE = {
    0: "連續除濕",
    1: "自動除濕",
    2: "防霉抑菌",
    4: "衣物乾燥",
    5: "保持乾燥",
    6: "濕度設定",
    7: "空氣清淨",
}
DEHUMIDIFIER_AVAILABLE_FAN = {0: "自動", 1: "靜音", 2: "標準", 3: "急速"}
DEHUMIDIFIER_AVAILABLE_FAN_DIR = {
    0: "固定", 1: "下方向", 2: "上方向", 3: "廣角", 4: "下吹",
}

LABEL_CLIMATE = ""
LABEL_DEHUMIDIFIER = ""
LABEL_OUTDOOR_TEMPERATURE = "室外溫度"
LABEL_NANOE = "nanoe"
LABEL_NANOEX = "nanoeX"
LABEL_ECONAVI = "ECONAVI"
LABEL_BUZZER = "操作提示音"
LABEL_TURBO = "急速"
LABEL_CLIMATE_SLEEP = "舒眠"
LABEL_CLIMATE_MOLD_PREVENTION = "乾燥防霉"
LABEL_CLIMATE_CLEAN = "自體淨"
LABEL_CLIMATE_INDICATOR = "機體燈光"
LABEL_CLIMATE_MOTION = "動向感應"
LABEL_CLIMATE_SWING_LR = "左右風向"
LABEL_CLIMATE_ON_TIMER = "定時開機"
LABEL_CLIMATE_OFF_TIMER = "定時關機"
LABEL_PM25 = "PM2.5"
LABEL_PM10 = "PM1.0"
LABEL_OPERATING_POWER = "即時功率"
LABEL_FILTER_NOTIFY = "濾網清洗通知"
LABEL_HUMIDITY = "環境溼度"
LABEL_TANK = "水箱滿水"
LABEL_DH_FAN = "風量設定"
LABEL_DH_FAN_DIR = "風向設定"
LABEL_DH_ON_TIMER = "定時開機"
LABEL_DH_OFF_TIMER = "定時關機"
LABEL_RF_FREEZER_SET = "冷凍溫度設定"
LABEL_RF_FRIDGE_SET = "冷藏溫度設定"
LABEL_RF_PARTIAL_SET = "微凍結溫度設定"
LABEL_RF_FREEZER_TEMP = "冷凍溫度"
LABEL_RF_FRIDGE_TEMP = "冷藏溫度"
LABEL_RF_PARTIAL_TEMP = "微凍結溫度"
LABEL_RF_DEFROST = "除霜中"
LABEL_RF_ECO = "ECONAVI"
LABEL_RF_STOP_ICE = "製冰停止"
LABEL_RF_QUICK_ICE = "快速製冰"
LABEL_RF_RAPID = "新鮮急凍結"
LABEL_RF_WINTER = "冬月模式"
LABEL_RF_SHOPPING = "購物模式"
LABEL_RF_VACATION = "度假模式"

ICON_CLIMATE = "mdi:air-conditioner"
ICON_THERMOMETER = "mdi:thermometer"
ICON_NANOE = "mdi:atom"
ICON_ECONAVI = "mdi:leaf"
ICON_BUZZER = "mdi:volume-high"
ICON_TURBO = "mdi:clock-fast"
ICON_SLEEP = "mdi:sleep"
ICON_MOLD_PREVENTION = "mdi:weather-windy"
ICON_LIGHT = "mdi:lightbulb-on-outline"
ICON_CLEAN = "mdi:broom"
ICON_MOTION = "mdi:motion-sensor"
ICON_SWING_LR = "mdi:arrow-left-right"
ICON_ON_TIMER = "mdi:alarm"
ICON_OFF_TIMER = "mdi:alarm-snooze"
ICON_PM25 = "mdi:dots-hexagon"
ICON_POWER = "mdi:flash"
ICON_FILTER = "mdi:air-filter"
ICON_HUMIDITY = "mdi:water-percent"
ICON_TANK = "mdi:cup-water"
ICON_FAN = "mdi:fan"
ICON_FAN_DIR = "mdi:arrow-up-down"
ICON_FREEZER = "mdi:snowflake"
ICON_FRIDGE = "mdi:fridge-outline"
ICON_ICE = "mdi:ice-cream"
ICON_DEFROST = "mdi:car-defrost-rear"

UNIT_MINUTE = "分鐘"
UNIT_HOUR = "小時"

# AC switch/select/number (type-gated in platforms)
SWITCH_DEFINITIONS_AC = [
    (SVC_NANOE, STATUS[SVC_NANOE], LABEL_NANOE, ICON_NANOE, False, False),
    (SVC_ECONAVI, STATUS[SVC_ECONAVI], LABEL_ECONAVI, ICON_ECONAVI, False, True),
    (SVC_TURBO, STATUS[SVC_TURBO], LABEL_TURBO, ICON_TURBO, False, False),
    (SVC_SLEEP, STATUS[SVC_SLEEP], LABEL_CLIMATE_SLEEP, ICON_SLEEP, False, True),
    (SVC_MOLD, STATUS[SVC_MOLD], LABEL_CLIMATE_MOLD_PREVENTION, ICON_MOLD_PREVENTION, False, True),
    (SVC_SELF_CLEAN, STATUS[SVC_SELF_CLEAN], LABEL_CLIMATE_CLEAN, ICON_CLEAN, False, True),
    (SVC_BUZZER, STATUS[SVC_BUZZER], LABEL_BUZZER, ICON_BUZZER, True, False),
]
SELECT_DEFINITIONS_AC = [
    (SVC_INDICATOR, STATUS[SVC_INDICATOR], LABEL_CLIMATE_INDICATOR, ICON_LIGHT, CLIMATE_AVAILABLE_INDICATOR),
    (SVC_MOTION, STATUS[SVC_MOTION], LABEL_CLIMATE_MOTION, ICON_MOTION, CLIMATE_AVAILABLE_MOTION),
    (SVC_SWING_LR, STATUS[SVC_SWING_LR], LABEL_CLIMATE_SWING_LR, ICON_SWING_LR, CLIMATE_AVAILABLE_SWING_LR),
]
NUMBER_DEFINITIONS_AC = [
    (SVC_TIMER_ON, STATUS[SVC_TIMER_ON], LABEL_CLIMATE_ON_TIMER, ICON_ON_TIMER, 0, 1440, True, UNIT_MINUTE),
    (SVC_TIMER_OFF, STATUS[SVC_TIMER_OFF], LABEL_CLIMATE_OFF_TIMER, ICON_OFF_TIMER, 0, 1440, False, UNIT_MINUTE),
]

SWITCH_DEFINITIONS_DH = [
    (SVC_DH_NANOE, STATUS[SVC_DH_NANOE], LABEL_NANOEX, ICON_NANOE, False, False),
    (SVC_DH_BUZZER, STATUS[SVC_DH_BUZZER], LABEL_BUZZER, ICON_BUZZER, True, False),
]
SELECT_DEFINITIONS_DH = [
    (SVC_DH_FAN, STATUS[SVC_DH_FAN], LABEL_DH_FAN, ICON_FAN, DEHUMIDIFIER_AVAILABLE_FAN),
    (SVC_DH_FAN_DIR, STATUS[SVC_DH_FAN_DIR], LABEL_DH_FAN_DIR, ICON_FAN_DIR, DEHUMIDIFIER_AVAILABLE_FAN_DIR),
]
NUMBER_DEFINITIONS_DH = [
    (SVC_DH_ON_TIMER, STATUS[SVC_DH_ON_TIMER], LABEL_DH_ON_TIMER, ICON_ON_TIMER, 0, 12, True, UNIT_HOUR),
    (SVC_DH_OFF_TIMER, STATUS[SVC_DH_OFF_TIMER], LABEL_DH_OFF_TIMER, ICON_OFF_TIMER, 0, 12, False, UNIT_HOUR),
]

SWITCH_DEFINITIONS_RF = [
    (SVC_RF_STOP_ICE, STATUS[SVC_RF_STOP_ICE], LABEL_RF_STOP_ICE, ICON_ICE, False, False),
    (SVC_RF_QUICK_ICE, STATUS[SVC_RF_QUICK_ICE], LABEL_RF_QUICK_ICE, ICON_ICE, False, False),
]
SELECT_DEFINITIONS_RF = [
    # option_map None → build from service range
    (SVC_RF_FREEZER_SET, STATUS[SVC_RF_FREEZER_SET], LABEL_RF_FREEZER_SET, ICON_FREEZER, None),
    (SVC_RF_FRIDGE_SET, STATUS[SVC_RF_FRIDGE_SET], LABEL_RF_FRIDGE_SET, ICON_FRIDGE, None),
    (SVC_RF_PARTIAL_SET, STATUS[SVC_RF_PARTIAL_SET], LABEL_RF_PARTIAL_SET, ICON_FREEZER, None),
]

ENTITY_SERVICES_BY_TYPE = {
    TYPE_AC: [
        SVC_POWER, SVC_MODE, SVC_FAN, SVC_TEMP_SET, SVC_TEMP_IN, SVC_SLEEP, SVC_NANOE,
        SVC_TIMER_ON, SVC_TIMER_OFF, SVC_SWING, SVC_SWING_LR, SVC_FILTER_NOTIFY,
        SVC_MOLD, SVC_SELF_CLEAN, SVC_MOTION, SVC_TURBO, SVC_ECONAVI, SVC_BUZZER,
        SVC_INDICATOR, SVC_TEMP_OUT, SVC_OPERATING_POWER, SVC_PM25, SVC_PM25_FLAG,
    ],
    TYPE_DEHUMIDIFIER: [
        SVC_POWER, SVC_MODE, SVC_DH_OFF_TIMER, SVC_DH_HUMIDITY_SET, SVC_DH_HUMIDITY_IN,
        SVC_DH_FAN_DIR, SVC_DH_TANK, SVC_DH_NANOE, SVC_DH_FAN, SVC_DH_BUZZER,
        SVC_DH_PM25, SVC_DH_ON_TIMER, SVC_DH_PM10,
    ],
    TYPE_REFRIGERATOR: [
        SVC_RF_FREEZER_SET, SVC_RF_FRIDGE_SET, SVC_RF_FREEZER_TEMP, SVC_RF_FRIDGE_TEMP,
        SVC_RF_ECO, SVC_RF_DEFROST, SVC_RF_STOP_ICE, SVC_RF_QUICK_ICE, SVC_RF_RAPID_FREEZE,
        SVC_RF_PARTIAL_SET, SVC_RF_PARTIAL_TEMP, SVC_RF_WINTER, SVC_RF_SHOPPING,
        SVC_RF_VACATION, SVC_RF_NANOE,
    ],
}

# Back-compat aliases used by older platform code
STATUS_POWER = STATUS[SVC_POWER]
STATUS_MODE = STATUS[SVC_MODE]
STATUS_FAN = STATUS[SVC_FAN]
STATUS_TEMP_SET = STATUS[SVC_TEMP_SET]
STATUS_TEMP_IN = STATUS[SVC_TEMP_IN]
STATUS_SLEEP = STATUS[SVC_SLEEP]
STATUS_NANOE = STATUS[SVC_NANOE]
STATUS_TIMER_ON = STATUS[SVC_TIMER_ON]
STATUS_TIMER_OFF = STATUS[SVC_TIMER_OFF]
STATUS_SWING = STATUS[SVC_SWING]
STATUS_SWING_LR = STATUS[SVC_SWING_LR]
STATUS_FILTER_NOTIFY = STATUS[SVC_FILTER_NOTIFY]
STATUS_MOLD = STATUS[SVC_MOLD]
STATUS_SELF_CLEAN = STATUS[SVC_SELF_CLEAN]
STATUS_MOTION = STATUS[SVC_MOTION]
STATUS_TURBO = STATUS[SVC_TURBO]
STATUS_ECONAVI = STATUS[SVC_ECONAVI]
STATUS_BUZZER = STATUS[SVC_BUZZER]
STATUS_INDICATOR = STATUS[SVC_INDICATOR]
STATUS_TEMP_OUT = STATUS[SVC_TEMP_OUT]
STATUS_OPERATING_POWER = STATUS[SVC_OPERATING_POWER]
STATUS_PM25 = STATUS[SVC_PM25]
STATUS_PM25_FLAG = STATUS[SVC_PM25_FLAG]
SWITCH_DEFINITIONS = SWITCH_DEFINITIONS_AC
SELECT_DEFINITIONS = SELECT_DEFINITIONS_AC
NUMBER_DEFINITIONS = NUMBER_DEFINITIONS_AC
ENTITY_SERVICES = ENTITY_SERVICES_BY_TYPE[TYPE_AC]
